### ISSUE TITLE
IRAM and DRAM requirements of TI-RTOS

### ISSUE THREAD

**Issue by vinayashreeks** [remixed123/startproject_cc3200_ti-rtos#1]
I am a newbie and want to use ti-rtos on beaglebone black. I want to know what is dram and iram requirements of ti-rtos.so that i can check whether it suits for my application.
I searched but not able to get the details.can anyone help me??
@remixed123 @beagleboneblack @tirtos

**Comment by remixed123** [comment]
You are obviously a newbie. This is not a free support channel. This project has nothing to do with the beagle bone.
